name       : python-parso
version    : 0.7.0
release    : 8
source     :
    - https://github.com/davidhalter/parso/archive/v0.7.0.tar.gz : ff2c9483e2aaba5f89f47d1fcc2b81f1fc6973cdba5001f88bfbbeacf7254cf3
license    :
    - MIT
    - Python-2.0
component  : programming.python
summary    : A Python Parser
description: |
    Parso is a Python parser that supports error recovery and round-trip parsing for different Python versions (in multiple Python versions). Parso is also able to list multiple syntax errors in your python file.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test pytest
    %python3_test pytest3
