name       : python-parso
version    : 0.7.1
release    : 9
source     :
    - https://github.com/davidhalter/parso/archive/refs/tags/v0.7.1.tar.gz : bc87a8272d4074394a92917b7e2edc3468ddf6511ca626b92243db8465e9cf6c
license    :
    - MIT
    - Python-2.0
component  : programming.python
summary    : A Python Parser
description: |
    Parso is a Python parser that supports error recovery and round-trip parsing for different Python versions (in multiple Python versions). Parso is also able to list multiple syntax errors in your python file.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test pytest
    %python3_test pytest3
