name       : python-parso
version    : 0.3.4
release    : 5
source     :
    - https://github.com/davidhalter/parso/archive/v0.3.4.tar.gz : 183f290db0ff1f005a0611bbb29b7dd29eb8cb1258ed5c7366c2dcdc4a1bb09f
license    :
    - MIT
    - Python-2.0
component  : programming.python
summary    : A Python Parser
description: |
    Parso is a Python parser that supports error recovery and round-trip parsing for different Python versions (in multiple Python versions). Parso is also able to list multiple syntax errors in your python file.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
