name       : python-parso
version    : 0.5.1
release    : 7
source     :
    - https://github.com/davidhalter/parso/archive/v0.5.1.tar.gz : 7fbdc177a40a16858fef77cd86efb5b1c50c0789a59642d7d0d05ac92c0dae10
license    :
    - MIT
    - Python-2.0
component  : programming.python
summary    : A Python Parser
description: |
    Parso is a Python parser that supports error recovery and round-trip parsing for different Python versions (in multiple Python versions). Parso is also able to list multiple syntax errors in your python file.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test pytest
    %python3_test pytest3 
