name       : python-parso
version    : 0.3.1
release    : 4
source     :
    - https://github.com/davidhalter/parso/archive/v0.3.1.tar.gz : 123485ea6b5b8b782535fd97d65ab647b98e34329bdf88f66d81d80f25784098
license    :
    - MIT
    - Python-2.0
component  : programming.python
summary    : A Python Parser
description: |
    Parso is a Python parser that supports error recovery and round-trip parsing for different Python versions (in multiple Python versions). Parso is also able to list multiple syntax errors in your python file.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
